# .github/workflows/cicd_pipeline.yml

name: Deploy AIOps Agent and Dashboard

on:
  push:
    branches:
    - main

env:
  # Set the AWS Region for all jobs
  AWS_REGION: us-east-1
  # Define ONLY the repository name. The full URL will be constructed later.
  ECR_REPOSITORY_NAME: ${{ secrets.PROJECT_NAME }}/frontend

jobs:
  deploy-backend:
    name: Deploy Backend Infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      ecr_repo_url: ${{ steps.tf-apply.outputs.ecr_repository_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies and prepare model
      run: |
        # 1. Install dependencies for Lambdas that DON'T use the layer
        pip install -r src/log_analyzer_rca/requirements.txt -t src/log_analyzer_rca/
        pip install -r src/remediation_engine/requirements.txt -t src/remediation_engine/

        # 2. Install dependencies FOR the layer
        pip install -r lambda_layers/requirements.txt -t lambda_layers/python/

        # 3. Train the ML model
        echo "Training model..."
        pip install -r scripts/requirements.txt
        # The model must exist for this step to succeed. 
        # Ensure you have run train_model.py locally and committed model.joblib.

        # 4. Copy the trained model INTO the layer directory
        echo "Copying model into layer..."
        cp src/anomaly_detector/model.joblib lambda_layers/python/

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform -chdir=infrastructure init

    - name: Terraform Apply
      id: tf-apply
      run: |
        terraform -chdir=infrastructure apply -auto-approve \
          -var="alert_email=${{ secrets.ALERT_EMAIL }}" \
          -var="project_name=${{ secrets.PROJECT_NAME }}" \
          -var="ec2_key_name=${{ secrets.EC2_KEY_NAME }}"
        echo "ecr_repository_url=$(terraform -chdir=infrastructure output -raw ecr_repository_url)" >> $GITHUB_OUTPUT

  build-and-deploy-frontend:
    name: Build and Deploy Frontend Dashboard
    runs-on: ubuntu-latest
    needs: deploy-backend
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:latest ./frontend
        docker push --all-tags $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}
